CREATE TABLE pontes(
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	nome VARCHAR(50),
	descricao TEXT,
	via VARCHAR(50),
	data_construcao DATE,
	trem_tipo VARCHAR(50),
	sentido VARCHAR(50),
	localizacao VARCHAR(100),
	latitude VARCHAR(100),
	longitude VARCHAR(100),
	projetista VARCHAR(100),
	construtor VARCHAR(100),
	comprimento_estrutura NUMERIC(8,2),
	largura_estrutura NUMERIC(8,2),
	largura_acostamento NUMERIC(8,2),
	largura_refugio NUMERIC(8,2),
	largura_passeio NUMERIC(8,2),
	sistema_construtivo VARCHAR(50),
	natureza_transposicao VARCHAR(50),
	material_construcao VARCHAR(50),
	longitudinal_super VARCHAR(50),
	transversal_super VARCHAR(50),
	mesoestrutura_tipo VARCHAR(50),
	nro_vaos INT,	
	nro_apoios INT,	
	nro_pilares_apoio INT,	
	aparelhos_apoio VARCHAR(50),
	comprimento_vao_tipico NUMERIC(8,2),
	comprimento_maior_vao NUMERIC(8,2),
	altura_pilares NUMERIC(8,2),
	juntas_dilatacao VARCHAR(50),
	encontros INT,
	outras TEXT,
	caracteristicas_plani VARCHAR(100),
	nro_faixas INT,
	acostamento VARCHAR(50),
	refugios VARCHAR(50),
	passeio VARCHAR(50),
	barreira_rigida VARCHAR(50),
	material_pavimento VARCHAR(50),
	pingadeiras VARCHAR(50),
	guarda_corpo VARCHAR(50),
	drenos VARCHAR(50),
	freq_passagem_carga VARCHAR(50),
	superestrutura VARCHAR(50),
	mesoestrutura VARCHAR(50),
	infraestrutura VARCHAR(50),
	aparelhos_apoio_anomalia VARCHAR(50),
	juntas_dilatacao_anomalia VARCHAR(50),
	encontros_anomalia VARCHAR(50),
	pavimento_anomalia VARCHAR(50),
	acostamento_refugio_anomalia VARCHAR(50),
	drenagem_anomalia VARCHAR(50),
	guarda_corpo_anomalia VARCHAR(50),
	barreira_defesa VARCHAR(50),
	taludes VARCHAR(50),
	iluminacao VARCHAR(50),
	sinalizacao VARCHAR(50),
	protecao_pilares VARCHAR(50)
);

CREATE TABLE imagens_pontes(
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	ponte_id INT NOT NULL REFERENCES pontes(id),
	imagem VARCHAR(200) NOT NULL
);

CREATE TABLE agendamentos(
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	data DATE NOT NULL,
	horario TIME NOT NULL,
	detalhes TEXT NOT NULL,
	ponte_id INT NOT NULL REFERENCES pontes(id)
);

CREATE TABLE usuarios(
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	usuario VARCHAR(50) NOT NULL unique,
	senha VARCHAR(60) NOT NULL
);